### ISSUE TITLE
Alterar o rodapé de 2014 Thomas Wohlke para 2016 Douglas Oliveira

### ISSUE THREAD

**Issue by douglas1014** [thomaswoehlke/javaee7-petclinic#39]

**Comment by phasenraum2010** [comment]
please write your issue in english

**Comment by masmangan** [comment]
Sorry, Thomas! This issue belongs to another repositoy, a fork from a programming class. Please ignore this.

**Comment by phasenraum2010** [comment]
@masmangan may I ask you what programming class is it?
